INSERT INTO `prosulcontratos`.`produto`
(`id`,
`produto_id`,
`empreendimento_id`,
`ordensdeservico_id`,
`numero`,
`datacadastro`,
`data_validade`,
`data_renovacao`,
`data_entrega`,
`fase`,
`entrega`,
`servico`,
`descricao`,
`aprov_data`,
`aprov_tempo_ultima_revisao`,
`aprov_tempo_total`,
`aprov_versao`,
`diretorio_texto`,
`diretorio_link`)
VALUES
(<{id: }>,
<{produto_id: }>,
<{empreendimento_id: }>,
<{ordensdeservico_id: }>,
<{numero: }>,
<{datacadastro: CURRENT_TIMESTAMP}>,
<{data_validade: }>,
<{data_renovacao: }>,
<{data_entrega: }>,
<{fase: }>,
<{entrega: }>,
<{servico: }>,
<{descricao: }>,
<{aprov_data: }>,
<{aprov_tempo_ultima_revisao: }>,
<{aprov_tempo_total: }>,
<{aprov_versao: }>,
<{diretorio_texto: }>,
<{diretorio_link: }>);
